#!/usr/bin/env bash
#
# export-secrets.sh
# -----------------
# Collect every local secret into ONE plaintext bundle: each GitHub Actions
# secret NAME on a line, its VALUE on the next line. Use the bundle to copy
# values into GitHub, or feed it to restore-secrets.sh on another machine.
#
# Reads (must exist locally):
#   composeApp/google-services.json   -> GOOGLE_SERVICES_JSON_BASE64
#   composeApp/buildingbox.keystore   -> KEYSTORE_BASE64
#   keystore.properties               -> KEYSTORE_STORE_PASSWORD / KEY_ALIAS / KEY_PASSWORD
#
# Writes:
#   secrets/github-secrets.txt        (mode 600, gitignored)
#
# WARNING: the bundle contains real secrets in cleartext. NEVER commit or share it.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

GS="composeApp/google-services.json"
KS="composeApp/buildingbox.keystore"
KP="keystore.properties"
OUT_DIR="secrets"
OUT="$OUT_DIR/github-secrets.txt"

# single-line base64 (portable: openssl, not GNU/BSD base64)
b64()  { openssl base64 -A -in "$1"; }
# read a value from keystore.properties, strip CR/LF
prop() { grep -E "^$1=" "$KP" | head -n1 | cut -d= -f2- | tr -d '\r\n'; }

# --- verify sources ---
missing=0
for f in "$GS" "$KS" "$KP"; do
  [ -f "$f" ] || { echo "MISSING: $f" >&2; missing=1; }
done
[ "$missing" -eq 0 ] || { echo "Aborting: add the missing file(s) and re-run." >&2; exit 1; }

mkdir -p "$OUT_DIR"
umask 177   # files created below are rw------- (owner only)

emit() { printf '%s\n%s\n\n' "$1" "$2"; }

{
  echo "# BuildingBox - GitHub Actions secrets bundle"
  echo "# Generated by scripts/export-secrets.sh. CONTAINS REAL SECRETS - never commit or share."
  echo "# Format: secret NAME on a line, its VALUE on the next line."
  echo
  emit GOOGLE_SERVICES_JSON_BASE64 "$(b64 "$GS")"
  emit KEYSTORE_BASE64             "$(b64 "$KS")"
  emit KEYSTORE_STORE_PASSWORD     "$(prop storePassword)"
  emit KEYSTORE_KEY_ALIAS          "$(prop keyAlias)"
  emit KEYSTORE_KEY_PASSWORD       "$(prop keyPassword)"
} > "$OUT"

chmod 600 "$OUT"
echo "Wrote $ROOT/$OUT  (mode 600, gitignored)"
echo "5 secrets bundled: open it to copy into GitHub, or run restore-secrets.sh elsewhere."
